spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taskdb
    driver-class-name: org.postgresql.Driver
    username: taskuser
    password: taskpass123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true